### ISSUE TITLE
Disable/renable waypoint following/station keeping

### ISSUE THREAD

**Issue by JohnSumskas** [USYD-RowBot/usyd_vrx#21]

**Comment by Benjamiiiin** [comment]
#24 Made pull request with implementation. I tagged and closed control_ben branch, then created new control_ben branch from the updated master. Fine for automatic merge.

**Comment by Benjamiiiin** [comment]
Still need to add the disable request client to the actionlib server in the docking program.

**Comment by Benjamiiiin** [comment]
Added docking_ben branch with docking program integrated with waypoint follower enable/disable. Works okay on X250, will test on metabox before pull request.

**Comment by Benjamiiiin** [comment]
#25 Pull request addresses the issue. Merging and removing branch docking_ben.
