### ISSUE TITLE
Buoy Classification - Thread Template image classification

### ISSUE THREAD

**Issue by JohnSumskas** [USYD-RowBot/usyd_vrx#27]
Line 180 in vrx_vision/src/objhelper/buoy_classifier.py 
use threads instead of a for loop to make classification faster.

**Comment by JohnSumskas** [comment]
on Branch vision_nicky

**Comment by jocelynnnn030** [comment]
Finished threading code on branch classifier_thread.  I dont think the speed get improved. The actual classification costs about 0.05 sec but the pre processing costs about 0.6sec. Run test.py on classifier_thread branch to see details.
